# Generated by Django 6.0.3 on 2026-04-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-match_date']},
        ),
    ]
