# Generated by Django 6.0.3 on 2026-04-06 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0002_alter_game_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='match_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
