# Generated by Django 6.0.3 on 2026-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betapp', '0005_payment_checkout_request_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={},
        ),
        migrations.RemoveField(
            model_name='game',
            name='created_at',
        ),
        migrations.AddField(
            model_name='game',
            name='free_summary',
            field=models.TextField(default=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='match_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='premium_analysis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.IntegerField(default=200),
        ),
    ]
